title: Rains In "Bangalore"!!
author: sush
email: lets skip that for now. Shall we?
description: > # this means to ignore newlines until "baseurl:"
  It's been pouring in Bangalore for days without a sign of stopping. What might be the cause of this??

# social links
twitter_username: Woops. I'm not on twitter!
github_username:  sushmam98

theme: minima
